
// === VERIFIED MUSIC FILTER SYSTEM ===
const BLOCKED_AI_TERMS = [
  'suno',
  'udio',
  'boomy',
  'aiva',
  'ai generated',
  'generated by ai',
  'artificial intelligence music',
  'ai music'
];

const isVerifiedAuraTrack = (track) => {
  if (!track) return false;

  const artistName = (track.artist || track.artistName || '').toLowerCase();
  const songName = (track.title || track.name || '').toLowerCase();
  const combined = `${artistName} ${songName}`;

  const followers =
    track.followers ||
    track.artistFollowers ||
    track.popularity ||
    0;

  // reject AI/generated artists
  if (BLOCKED_AI_TERMS.some(term => combined.includes(term))) {
    return false;
  }

  // reject tiny artists
  if (followers < 50000) {
    return false;
  }

  return true;
};

import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";

export default defineConfig({
  plugins: [react(), tailwindcss()],
});
