
// === VERIFIED MUSIC FILTER SYSTEM ===
const BLOCKED_AI_TERMS = [
  'suno',
  'udio',
  'boomy',
  'aiva',
  'ai generated',
  'generated by ai',
  'artificial intelligence music',
  'ai music'
];

const isVerifiedAuraTrack = (track) => {
  if (!track) return false;

  const artistName = (track.artist || track.artistName || '').toLowerCase();
  const songName = (track.title || track.name || '').toLowerCase();
  const combined = `${artistName} ${songName}`;

  const followers =
    track.followers ||
    track.artistFollowers ||
    track.popularity ||
    0;

  // reject AI/generated artists
  if (BLOCKED_AI_TERMS.some(term => combined.includes(term))) {
    return false;
  }

  // reject tiny artists
  if (followers < 50000) {
    return false;
  }

  return true;
};

import React from "react";
import { createRoot } from "react-dom/client";
import App from "./App.jsx";
import ErrorBoundary from "./ErrorBoundary.jsx";
import "./index.css";

createRoot(document.getElementById("root")).render(
  <React.StrictMode>
    <ErrorBoundary>
      <App />
    </ErrorBoundary>
  </React.StrictMode>
);
